#!/usr/bin/env bash
# It installs Nginx with the following configurations:
#+   Listens on port 80.
#+   Returns a page containing "Hello World" when queried
#+   at the root with a curl GET request.
#+   It contains a custom HTTP header named X-Served-By.
#+   The value of the HTTP header is the hostname of the running server.


sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart

