#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on.
# Displays all acive IPv4 addresses on the machine.
ifconfig | grep 'inet addr:' | cut -d: -f2 | cut -d" " -f1

